# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- none

stages:
- stage: Build_SecureImage
  displayName: 'Build'
  jobs:
  # Set an output variable from a job with a matrix
  - job: A
    pool:
      vmImage: 'ubuntu-latest'
    strategy:
      maxParallel: 2
      matrix:
        debugJob:
          configuration: debug
          platform: x64
        releaseJob:
          configuration: release
          platform: x64
    steps:
    - script: echo "##vso[task.setvariable variable=myOutputVar;isOutput=true]this is the $(configuration) value"
      name: setvarStep
    - script: echo $(setvarStep.myOutputVar)
      name: echovar

  # Map the variable from the debug job
  - job: B
    dependsOn: A
    pool:
      vmImage: 'ubuntu-16.04'
    variables:
      myVarFromJobADebug: $[ dependencies.A.outputs['debugJob.setvarStep.myOutputVar'] ]
    steps:
    - script: echo $(myVarFromJobADebug)
      name: echovar

