parameters:
- name: imagesMenu
  displayName: Image Selection
  type: string
  default: ubuntu18_base
  values:
  - all
  - rlgroup
  - 2012R2_base
  - 2012R2_default
  - 2016_base
  - 2016_default
  - 2016_update
  - 2019_base
  - 2019_default
  - 2019_md
  - ubuntu18_base
  - ubuntu18_ansible
- name: osMenu
  displayName: Select OS
  type: string
  default: linux
  values:
  - default
  - all
  - windows
  - linux
  - vmware
- name: imageVarFile
  displayName: Select Credentials
  type: string
  default: default
  values:
  - default
  - production
  - debug
  - all
- name: providerMenu
  displayName: Select Provider
  type: string
  default: azure
  values:
  - default
  - aws
  - azure
  - vcenter
  - all
- name: runtime
  displayName: Select Runtime
  type: string
  default: ansible
  values:
  - packer
  - terraform
  - ansible
  - packer-terraform-ansible
  - services
- name: ansible
  displayName: Select Ansible Build
  type: string
  default: default
  values:
  - default
  - production
  - build
  - debug
- name: configs
  type: string
  default: 'x86,x64'
- name: tenant
  displayName: Select tenant
  type: string
  default: default
  values:
  - default
  - KcStandAlone
  - KcCluster
- name: job
  displayName: Select Job to Run
  type: string
  default: default
  values:
  - default
  - poweron
  - poweroff
  - status

trigger: none

variables:
  deploymentLabel: 'idp'
  imageID: 'placeholder'

stages:
- template: /idp/providers.yaml
  parameters:
    platform: windows
    providers:
      - name: aws
      - name: azure
    imagesMenu: ${{ parameters.imagesMenu }}
    osMenu: ${{ parameters.osMenu }}
    imageVarFile: ${{ parameters.imageVarFile }}
    providerMenu: ${{ parameters.providerMenu }}
    runtime: ${{ parameters.runtime }}
    ansible: ${{ parameters.ansible }}
    tenant: ${{ parameters.tenant }}
    job: ${{ parameters.job }}