# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

stages:
  stage: One_Initialize
  displayName: 'Initialize'
  jobs:
    job: Stage1_Job1
    displayName: 'Initialize - Job1'
    steps:
      task: Bash@3
      displayName: packer wget, unzip
      inputs:
        targetType: 'inline'
        script:
          VER=1.4.5
          wget https://releases.hashicorp.com/packer/${VER}/packer_${VER}_linux_amd64.zip
          unzip packer_${VER}_linux_amd64.zip
          sudo mv packer /usr/local/bin
          packer --version

      task: Bash@3
      displayName: terraform
      inputs:
        targetType: 'inline'
        script:
          VER=0.12.9
          wget --no-verbose https://releases.hashicorp.com/terraform/${VER}/terraform_${VER}_linux_amd64.zip
          sudo unzip ./terraform_${VER}_linux_amd64.zip -d /usr/local/bin/
          terraform -v
  stage: Two_Initialize
  displayName: 'Initialize2'
  jobs:
    job: Stage2_Job1
    displayName: 'Initialize - Job1'
    steps:
      task: Bash@3
      displayName: packer wget, unzip
      inputs:
        targetType: 'inline'
        script:
          packer --version

      task: Bash@3
      displayName: terraform
      inputs:
        targetType: 'inline'
        script:
          terraform -v