# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'


steps:
- task: Bash@3
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Packer'

- script: |
    VER=1.4.5
    wget https://releases.hashicorp.com/packer/${VER}/packer_${VER}_linux_amd64.zip
    unzip packer_${VER}_linux_amd64.zip
    sudo mv packer /usr/local/bin
    packer --version
  displayName: 'Packer install and build'

- task: Bash@3
  inputs:
    versionSpec: '11.x'
  displayName: 'Install Terraform'

- script: |
    VER=0.12.9
    wget --no-verbose https://releases.hashicorp.com/terraform/${VER}/terraform_${VER}_linux_amd64.zip
    sudo unzip ./terraform_${VER}_linux_amd64.zip -d /usr/local/bin/
    terraform -v
  displayName: 'Terraform install and build'