# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- none

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Build_SecureImage
  displayName: 'Build'
  jobs:
  - job: Foo
    steps:
      - script: |
          echo "This is job Foo."
          echo "##vso[task.setvariable variable=doThing;isOutput=true]aws" #The variable doThing is set to aws
        name: DetermineResult
  - job: aws
    dependsOn: Foo
    condition: eq(dependencies.Foo.outputs['DetermineResult.doThing'], 'aws') #map doThing and check if true
    steps:
      - script: echo "Job aws ran and doThing is aws."
  - job: azure
    dependsOn: Foo
    condition: eq(dependencies.Foo.outputs['DetermineResult.doThing'], 'azure') #map doThing and check if true
    steps:
      - script: echo "Job azure ran and doThing is azure."

- stage: Build_SecureImage2
  displayName: 'Build2'
  jobs:
  - job: Install
    steps:
      - script: |
          echo "apt-get update"
          sudo apt-get install curl jq -y
          sudo apt-get update
          echo "##vso[task.setvariable variable=doThing2;isOutput=true]azure"
        name: DetermineResult2
  - job: aws
    dependsOn: Install
    condition: eq(dependencies.Install.outputs['DetermineResult2.doThing2'], 'aws') 
    steps:
      - script: echo "Job aws ran and doThing is aws."
  - job: azure
    dependsOn: Install
    condition: eq(dependencies.Install.outputs['DetermineResult2.doThing2'], 'azure') 
    steps:
      - script: echo "Job azure ran and doThing is azure."

  - job: Install AWS CLI
    steps:
    - task: Bash@3
    displayName: 'Install AWS CLI'
    inputs:
      targetType: 'inline'
      script: |
          sudo apt-get update
          sudo apt-get install awscli -y
          export AWS_ACCESS_KEY_ID=$(AWS_ACCESS_KEY_ID)
          export AWS_SECRET_ACCESS_KEY=$(aws_secret_access_key)
          export AWS_DEFAULT_REGION=$(AWS_DEFAULT_REGION)
          aws --version
          aws s3 ls
  - job: Packer
    steps:  
    - task: Bash@3
      displayName: 'Install Packer'
      inputs:
        targetType: 'inline'
        script: |
            VER=1.4.5
            wget https://releases.hashicorp.com/packer/${VER}/packer_${VER}_linux_amd64.zip
            # unzip packer_${VER}_linux_amd64.zip
            # sudo mv packer /usr/local/bin
            packer --version