jobs:
- ${{ if contains(parameters.stage, 'build') }}:
  - job: 'buildVars'
    steps:
    - script: |
        echo '${{ parameters.runtime }}'
        echo '${{ parameters.imagesMenu }}'
        echo '${{ parameters.osMenu }}'
      displayName: 'buildVars'
- ${{ if contains(parameters.stage, 'launch') }}:
#- ${{ if and( ne('${{ parameters.imagesMenu }}', 'all'), eq('${{ parameters.imagesMenu }}', 'rlgroup') ) }}:
  - job: 'launchVars'
    steps:
    - script: |
        echo '${{ parameters.runtime }}'
        echo '${{ parameters.imagesMenu }}'
        echo '${{ parameters.osMenu }}'
      displayName: 'launchVars'

- ${{ if contains(parameters.stage, 'build') }}:
#- ${{ if and( contains('${{ parameters.imagesMenu }}', '_'), eq('${{ parameters.runtime }}', 'packerOnly') ) }}:
  - template: /idp/build.yaml
    parameters:
      stage: build
      imageVarFile: ${{ parameters.imageVarFile }}
      providerMenu: ${{ parameters.providerMenu }}
      provider: ${{ parameters.provider }}
      imagesMenu: ${{ parameters.imagesMenu }}
      osMenu: ${{ parameters.osMenu }}
      runtime: ${{ parameters.runtime }}
      images:
      - name: ${{ parameters.imagesMenu }}
        providers:
        - ${{ parameters.providerMenu }}
        description: buildSingle

- ${{ if contains(parameters.stage, 'launch') }}:
#- ${{ if and( eq('${{ parameters.runtime }}', 'terraformOnlyNoShutdown'), eq('${{ parameters.providerMenu }}', 'azure') ) }}:
  - template: /idp/launch.yaml
    parameters:
      stage: launch
      imageVarFile: ${{ parameters.imageVarFile }}
      providerMenu: ${{ parameters.providerMenu }}
      provider: ${{ parameters.provider }}
      imagesMenu: ${{ parameters.imagesMenu }}
      osMenu: ${{ parameters.osMenu }}
      runtime: ${{ parameters.runtime }}
      images:
      - name: ${{ parameters.imagesMenu }}
        providers:
        - ${{ parameters.providerMenu }}
        description: launchSingle