jobs:
- ${{ if eq(parameters.runtime, 'production') }}:
  - job: 'productionVarsYaml'
    steps:
    - script: |
        echo '${{ parameters.runtime }}'
        echo '${{ parameters.imagesMenu }}'
        echo '${{ parameters.osMenu }}'
      displayName: 'productionVarsYaml'
- ${{ if eq(parameters.imagesMenu, 'all') }}:
  - template: /idp/images.yaml
    #condition: and( eq('${{ parameters.imagesMenu }}', 'all'), ne('${{ parameters.imagesMenu }}', 'rlgroup') )
    parameters:
      provider: ${{ parameters.provider }}
      imagesMenu: ${{ parameters.imagesMenu }}
      osMenu: ${{ parameters.osMenu }}
      runtime: ${{ parameters.runtime }}
      images:
      - name: 2012R2_base
        providers:
        - azure
        description: Server 2012R2 Base
      - name: 2012R2_default
        providers:
        - aws
        description: Server 2012R2 Default
- ${{ if eq(parameters.imagesMenu, 'rlgroup') }}:
  - template: /idp/images.yaml
    #condition: and( ne('${{ parameters.imagesMenu }}', 'all'), eq('${{ parameters.imagesMenu }}', 'rlgroup') )
    parameters:
      provider: ${{ parameters.provider }}
      imagesMenu: ${{ parameters.imagesMenu }}
      osMenu: ${{ parameters.osMenu }}
      runtime: ${{ parameters.runtime }}
      images:
      - name: rl_test1
        providers:
        - azure
        description: rl_test1
      - name: rl_test2
        providers:
        - azure
        description: rl_test2
      - name: rl_test3
        providers:
        - azure
        description: rl_test3
- ${{ if contains(parameters.imagesMenu, '_') }}:
#- ${{ if and( ne('${{ parameters.imagesMenu }}', 'all'), ne('${{ parameters.imagesMenu }}', 'rlgroup') ) }}:
  - template: /idp/images.yaml
    parameters:
      provider: ${{ parameters.provider }}
      imagesMenu: ${{ parameters.imagesMenu }}
      osMenu: ${{ parameters.osMenu }}
      runtime: ${{ parameters.runtime }}
      images:
      - name: ${{ parameters.imagesMenu }}
        providers:
        - ${{ parameters.providerMenu }}
        description: testingSingle