jobs:
  - job: 'createPool'
    pool:
      ${{ if eq(parameters.runtime, 'production') }}:
        vmImage: 'ubuntu-latest'
      ${{ if eq(parameters.runtime, 'build') }}:
        vmImage: 'ubuntu-latest'
    strategy:
      matrix:
        ${{ each image in parameters.images }}:
          ${{ if eq(image.providers[0], '') }}:
            ${{ image.name }}:
              ImageName: ${{ image.name }}
              ImageDescription: 'Description-${{ image.name }}'
          ${{ if ne(image.providers[0], '') }}:
            ${{ each provider in image.providers }}:
              ${{ if eq( provider, parameters.provider) }}:
                ${{ image.name }}:
                  ImageName: ${{ image.name }}
                  ImageDescription: 'Description-${{ image.name }}'
    steps:
    - script: |
        echo '${{ parameters.runtime }}'
        echo '${{ parameters.imagesMenu }}'
        echo '${{ parameters.osMenu }}'
      displayName: 'createPool'
  - ${{ if eq(parameters.runtime, 'production') }}:
    - job: 'packerProdVarImagesYaml'
      steps:
      - script: |
          echo '${{ parameters.runtime }}'
          echo '${{ parameters.imagesMenu }}'
          echo '${{ parameters.osMenu }}'
        displayName: 'packerProdVarImagesYaml'
  - ${{ if eq(parameters.runtime, 'build') }}:
    - job: 'packerProdImagesYaml'
      steps:
      - script: |
          echo '${{ parameters.runtime }}'
          echo '${{ parameters.imagesMenu }}'
          echo '${{ parameters.osMenu }}'
        displayName: 'packerProdImagesYaml'
  - ${{ if eq(parameters.runtime, 'build') }}:
    - job: 'packerBuildVarimagesYaml'
      steps:
      - script: |
          echo '${{ parameters.runtime }}'
          echo '${{ parameters.imagesMenu }}'
          echo '${{ parameters.osMenu }}'
        displayName: 'packerBuildVarimagesYaml'