parameters:
  # provider: ''
  images: []

jobs:
  - job: '${{ parameters.provider }}PackerBuild'
    pool:
      vmImage: 'ubuntu-latest'
    strategy:
      matrix:
        ${{ each image in parameters.images }}:
          ${{ if eq(image.providers[0], '') }}:
            ${{ image.name }}:
              ImageName: ${{ image.name }}
              ImageDescription: 'Description-${{ image.name }}'
          ${{ if ne(image.providers[0], '') }}:
            ${{ each provider in image.providers }}:
              ${{ if eq( provider, parameters.provider) }}:
                ${{ image.name }}:
                  ImageName: ${{ image.name }}
                  ImageDescription: 'Description-${{ image.name }}'
    steps:
    - script: |
        echo 'ImageName variable: $(ImageName)'
        echo 'ImageName Description: $(ImageDescription)'
        echo '${{ parameters.runtime }}'
        echo '${{ parameters.imagesMenu }}'
        echo '${{ parameters.osMenu }}'
        pwd
        ls
      displayName: 'PackerDebug'
    - script: |
        # VER=1.5.1
        # echo "Download File"
        # wget https://releases.hashicorp.com/packer/${VER}/packer_${VER}_linux_amd64.zip
        # echo "Unzip File and move to local bin"
        # sudo unzip packer_${VER}_linux_amd64.zip -d /usr/local/bin
        # echo "Get version"
        packer --version
      displayName: 'packerInstall'
    - script: |
        # VER=1.5.1
        # echo "Download File"
        # wget https://releases.hashicorp.com/packer/${VER}/packer_${VER}_linux_amd64.zip
        # echo "Unzip File and move to local bin"
        # sudo unzip packer_${VER}_linux_amd64.zip -d /usr/local/bin
        # echo "Get version"
        terraform -v
      displayName: 'terraformInstall'
    - script: |
        echo '********Setting Variables*********'
        export AWS_ACCESS_KEY_ID=$(AWS_ACCESS_KEY_ID)
        export AWS_SECRET_ACCESS_KEY=$(AWS_SECRET_ACCESSkey)
        export AWS_DEFAULT_REGION=$(AWS_DEFAULT_REGION)
        export ARM_CLIENT_ID=$(ARM_CLIENT_ID)
        export ARM_CLIENT_SECRET=$(ARM_CLIENT_SECRET)
        export ARM_SUBSCRIPTION_ID=$(ARM_SUBSCRIPTION_ID)
        export ARM_TENANT_ID=$(ARM_TENANT_ID)
        export PACKER_LOG_PATH="packer.log"
        export PACKER_LOG=1

        echo 'Setting Azure Creds to $(ARM_CLIENT_ID)'
        az login --service-principal --username $(ARM_CLIENT_ID) --password $(ARM_CLIENT_SECRET) --tenant $(ARM_TENANT_ID)
        #chmod +x ado_packer_image.sh
        #./ado_packer_image.sh "${{ parameters.providerMenu }}" "${{ parameters.osMenu }}" "${{ parameters.imagesMenu }}" "${{ parameters.imageVarFile }}"
      displayName: 'packer'
    - script: |
        echo '********Setting Variables*********'
      displayName: 'Logs Variables'