jobs:
- ${{ if eq(parameters.runtime, 'production') }}:
  - job: 'packerVarimagesYaml'
    steps:
    - script: |
        echo '${{ parameters.runtime }}'
        echo '${{ parameters.imagesMenu }}'
        echo '${{ parameters.osMenu }}'
      displayName: 'packerVarimagesYaml'
- ${{ if eq(parameters.runtime, 'build') }}:
  - job: 'packerImagesYaml'
    steps:
    - script: |
        echo '${{ parameters.runtime }}'
        echo '${{ parameters.imagesMenu }}'
        echo '${{ parameters.osMenu }}'
      displayName: 'packerImagesYaml'
- ${{ if eq(parameters.runtime, 'build') }}:
  - job: 'buildVarimagesYaml'
    steps:
    - script: |
        echo '${{ parameters.runtime }}'
        echo '${{ parameters.imagesMenu }}'
        echo '${{ parameters.osMenu }}'
      displayName: 'buildVarimagesYaml'