parameters:
  provider: ''
  stage: ''
  images: []

jobs:
  - job: 'createPool'
    pool:
      vmImage: 'ubuntu-latest'
    strategy:
      matrix:
        ${{ each image in parameters.images }}:
          ${{ if eq(image.providers[0], '') }}:
            ${{ image.name }}:
              ImageName: ${{ image.name }}
              ImageDescription: 'Description-${{ image.name }}'
          ${{ if ne(image.providers[0], '') }}:
            ${{ each provider in image.providers }}:
              ${{ if eq( provider, parameters.provider) }}:
                ${{ image.name }}:
                  ImageName: ${{ image.name }}
                  ImageDescription: 'Description-${{ image.name }}'
    steps:
    - script: |
        echo '${{ parameters.runtime }}'
        echo '${{ parameters.imagesMenu }}'
        echo '${{ parameters.osMenu }}'
      displayName: 'outputVars'
    - script: |
        echo '${{ parameters.runtime }}'
        echo '${{ parameters.imagesMenu }}'
        echo '${{ parameters.osMenu }}'
      displayName: 'packerProdVarImagesYaml'