stages:
- stage: 'OutputAllVars'
  jobs:
  - job: 'show_variables1'
    steps:
    - script: |
        echo '${{ parameters.platform }}'
        echo '${{ parameters.imagesMenu }}'
        echo '${{ parameters.osMenu }}'
        echo '${{ parameters.imageVarFile }}'
        echo '${{ parameters.providerMenu }}'
        echo '${{ parameters.runtime }}'
      displayName: 'Show variables used in menu'
  - job: 'show_variables2'
    steps: 
    - ${{ each test in parameters.providers }}:
      - script: echo ${{ test.name }}
        displayName: ${{ test.name }}

- ${{ each provider in parameters.providers }}:
  - stage: ${{ provider.name }}Init
    displayName: ${{ provider.name }} - Init
    dependsOn: OutputAllVars
    jobs:
    - job: initJob1
      steps:
      - script: |
          echo ${{ provider.name }}initJob1
        displayName: ${{ provider.name }}initJob1
  - stage: ${{ provider.name }}Build
    displayName: ${{ provider.name }} - Build
    dependsOn: ${{ provider.name }}Init
    condition: or( eq('${{ parameters.imagesMenu }}', 'all'), eq('${{ parameters.imagesMenu }}', 'rlgroup') )
    jobs:
    - job: buildjob1
      steps:
      - script: |
          echo ${{ provider.name }}buildjob1
        displayName: ${{ provider.name }}buildjob1
  - stage: ${{ provider.name }}Build2
    displayName: ${{ provider.name }} - Build2
    dependsOn: ${{ provider.name }}Build
    condition: or( eq('${{ parameters.imagesMenu }}', 'all'), eq('${{ parameters.imagesMenu }}', 'rlgroup') )
    jobs:
    - template: /packer/images.yaml
      parameters:
        provider: ${{ provider.name }}
        stage: build
        imagesMenu: ${{ parameters.imagesMenu }}
        osMenu: ${{ parameters.osMenu }}
        imageVarFile: ${{ parameters.imageVarFile }}
        providerMenu: ${{ parameters.providerMenu }}
        runtime: ${{ parameters.runtime }}
    #- job: ImageAvailJob
    #  steps: 
    #  - ${{ each test in parameters.imagesMenu }}:
    #    - script: echo ${{ test.name }}
    #      displayName: ${{ test.name }}ImagesAvailscript