stages:
- stage: 'Testing'
  jobs:
  - job: 'show_variables1'
    steps:
    - script: |
        echo 'one'
      displayName: 's1'
  - stage: 'Testing2'
    jobs:
    - job: 'show_variables2'
      steps:
      - script: |
          echo 'two'
        displayName: 's2'