stages:
- stage: 'Testing'
  jobs:
  - job: 'show_variables1'
    steps:
    - script: |
        echo 'one'
      displayName: 's1'
- ${{ each provider in parameters.providers }}:
  - stage: ${{ provider.name }}Init
    displayName: ${{ provider.name }} - Init
    dependsOn: Testing
    jobs:
    - job: initJob1
      steps:
      - script: |
          echo ${{ provider.name }}initJob1
        displayName: ${{ provider.name }}initJob1
  - stage: ${{ provider.name }}Build
    displayName: ${{ provider.name }} - Build
    dependsOn: ${{ provider.name }}Init
    #condition: eq( variable['provider'], 'all')
    jobs:
    - job: buildjob1
      steps:
      - script: |
          echo ${{ provider.name }}buildjob1
        displayName: ${{ provider.name }}buildjob1
    - job: show_variables2
      steps: 
      - ${{ each provider in parameters.providers }}:
        - script: echo ${{ provider.name }}