stages:
- stage: 'OutputAllVars'
  jobs:
  - job: 'show_variables1'
    steps:
    - script: |
        echo '${{ parameters.platform }}'
        echo '${{ parameters.imagesMenu }}'
        echo '${{ parameters.osMenu }}'
        echo '${{ parameters.imageVarFile }}'
        echo '${{ parameters.providerMenu }}'
        echo '${{ parameters.runtime }}'
      displayName: 'Show variables used in menu'
      condition: and( ne('${{ parameters.imagesMenu }}', 'all'), eq('${{ parameters.imagesMenu }}', 'ubuntu18_base') )
  - job: 'show_variables2'
    dependsOn: show_variables1
    condition: and( ne('${{ parameters.imagesMenu }}', 'all'), ne('${{ parameters.imagesMenu }}', 'ubuntu18_base') )
    steps: 
    - ${{ each test in parameters.providers }}:
      - script: echo ${{ test.name }}
        displayName: ${{ test.name }}

- ${{ each provider in parameters.providers }}:
  - stage: ${{ provider.name }}Init
    displayName: ${{ provider.name }} - Init
    dependsOn: OutputAllVars
    jobs:
    - job: initJob1
      steps:
      - script: |
          echo '${{ provider.name }}initJob1'
          echo '${{ parameters.platform }}'
          echo '${{ parameters.imagesMenu }}'
          echo '${{ parameters.osMenu }}'
          echo '${{ parameters.imageVarFile }}'
          echo '${{ parameters.providerMenu }}'
          echo '${{ parameters.runtime }}'
        displayName: ${{ provider.name }}initJob1

  - stage: ${{ provider.name }}Build
    displayName: ${{ provider.name }}Build
    dependsOn: ${{ provider.name }}Init
    condition: contains('${{ parameters.runtime }}', 'packer')
    jobs:
    - template: /images.yaml
      parameters:
        provider: ${{ provider.name }}
        stage: build
        imagesMenu: ${{ parameters.imagesMenu }}
        osMenu: ${{ parameters.osMenu }}
        imageVarFile: ${{ parameters.imageVarFile }}
        providerMenu: ${{ parameters.providerMenu }}
        runtime: ${{ parameters.runtime }}

  - stage: ${{ provider.name }}Launch
    displayName: ${{ provider.name }}Launch
    dependsOn: ${{ provider.name }}Build
    condition: contains('${{ parameters.runtime }}', 'terraform')
    jobs:
    - template: /images.yaml
      parameters:
        provider: ${{ provider.name }}
        stage: launch
        imagesMenu: ${{ parameters.imagesMenu }}
        osMenu: ${{ parameters.osMenu }}
        imageVarFile: ${{ parameters.imageVarFile }}
        providerMenu: ${{ parameters.providerMenu }}
        runtime: ${{ parameters.runtime }}

  - stage: ${{ provider.name }}Ansible
    displayName: ${{ provider.name }}Ansible
    jobs:
    - job: 'show_variables_ansible'
      steps:
      - script: |
          echo '${{ parameters.platform }}'
          echo '${{ parameters.imagesMenu }}'
          echo '${{ parameters.osMenu }}'
          echo '${{ parameters.imageVarFile }}'
          echo '${{ parameters.providerMenu }}'
          echo '${{ parameters.runtime }}'
          echo '${{ parameters.ansible }}'
        displayName: 'Ansible Vars'
        condition: contains('${{ parameters.runtime }}', 'ansible')
    - job: 'show_variables_ansible2'
      dependsOn: show_variables_ansible
      steps: 
      - script: |
          # VER=1.5.6
          # echo "Download File"
          # wget https://releases.hashicorp.com/packer/${VER}/packer_${VER}_linux_amd64.zip
          # echo "Unzip File and move to local bin"
          # sudo unzip packer_${VER}_linux_amd64.zip -d /usr/local/bin
          # echo "Get version"
          sudo apt-get update
          sudo apt-get install ansible -y
          sudo apt-get install python-pip -y
          pip install pywinrm
          ansible --version
        displayName: 'ansibleInstall'
        condition: contains('${{ parameters.runtime }}', 'ansible')













#  - stage: ${{ provider.name }}Buildall
#    displayName: ${{ provider.name }} - Buildall
#    dependsOn: ${{ provider.name }}Init
#    condition: and( ne('${{ parameters.imagesMenu }}', 'all'), eq('${{ parameters.imagesMenu }}', 'rlgroup') )
#    jobs:
#    - template: /packer/images.yaml
#      parameters:
#        provider: ${{ provider.name }}
#        stage: build
#        imagesMenu: ${{ parameters.imagesMenu }}
#        osMenu: ${{ parameters.osMenu }}
#        imageVarFile: ${{ parameters.imageVarFile }}
#        providerMenu: ${{ parameters.providerMenu }}
#        runtime: ${{ parameters.runtime }}

#  - stage: ${{ provider.name }}Buildsingle
#    displayName: ${{ provider.name }} - Buildsingle
#    dependsOn: ${{ provider.name }}Init
#    condition: and( ne('${{ parameters.imagesMenu }}', 'all'), ne('${{ parameters.imagesMenu }}', 'rlgroup') )
#    jobs:
#    - template: /packer/images.yaml
#      parameters:
#        provider: ${{ provider.name }}
#        stage: build
#        imagesMenu: ${{ parameters.imagesMenu }}
#        osMenu: ${{ parameters.osMenu }}
#        imageVarFile: ${{ parameters.imageVarFile }}
#        providerMenu: ${{ parameters.providerMenu }}
#        runtime: ${{ parameters.runtime }}