stages:
- stage: 'Testing'
  jobs:
  - job: 'show_variables1'
    steps:
    - script: |
        echo 'one'
      displayName: 's1'
- stage: 'Testing2'
  jobs:
  - job: 'show_variables2'
    steps:
    - script: |
        echo 'two'
      displayName: 's2'
- ${{ each provider in parameters.providers }}:
  - stage: ${{ provider.name }}Init
    displayName: ${{ provider.name }} - Init
    dependsOn: Testing2
    jobs:
    - job: init
      steps:
      - script: |
          echo 'test3job1'
        displayName: 'test3job1'