stages:
- stage: 'OutputAllVars'
  jobs:
  - job: 'show_variables1'
    steps:
    - script: |
        echo '${{ parameters.platform }}'
        echo '${{ parameters.imagesMenu }}'
        echo '${{ parameters.osMenu }}'
        echo '${{ parameters.imageVarFile }}'
        echo '${{ parameters.providerMenu }}'
        echo '${{ parameters.runtime }}'
        echo '${{ parameters.tenant }}'
        echo '${{ parameters.job }}'
      displayName: 'Show variables used in menu'
  - job: 'show_variables2'
    dependsOn: show_variables1
    condition: and( ne('${{ parameters.imagesMenu }}', 'all'), ne('${{ parameters.imagesMenu }}', 'ubuntu18_base') )
    steps: 
    - ${{ each test in parameters.providers }}:
      - script: echo ${{ test.name }}
        displayName: ${{ test.name }}

- ${{ each provider in parameters.providers }}:
  - stage: ${{ provider.name }}Init
    displayName: ${{ provider.name }} - Init
    dependsOn: OutputAllVars
    jobs:
    - job: initJob1
      steps:
      - script: |
          echo '${{ provider.name }}initJob1'
          echo '${{ parameters.platform }}'
          echo '${{ parameters.imagesMenu }}'
          echo '${{ parameters.osMenu }}'
          echo '${{ parameters.imageVarFile }}'
          echo '${{ parameters.providerMenu }}'
          echo '${{ parameters.runtime }}'
        displayName: ${{ provider.name }}initJob1

  - stage: ${{ provider.name }}Build
    displayName: ${{ provider.name }}Build
    dependsOn: ${{ provider.name }}Init
    condition: contains('${{ parameters.runtime }}', 'packer')
    jobs:
    - template: /images.yaml
      parameters:
        provider: ${{ provider.name }}
        stage: build
        imagesMenu: ${{ parameters.imagesMenu }}
        osMenu: ${{ parameters.osMenu }}
        imageVarFile: ${{ parameters.imageVarFile }}
        providerMenu: ${{ parameters.providerMenu }}
        runtime: ${{ parameters.runtime }}

  - stage: ${{ provider.name }}Launch
    displayName: ${{ provider.name }}Launch
    dependsOn: ${{ provider.name }}Build
    condition: contains('${{ parameters.runtime }}', 'terraform')
    jobs:
    - template: /images.yaml
      parameters:
        provider: ${{ provider.name }}
        stage: launch
        imagesMenu: ${{ parameters.imagesMenu }}
        osMenu: ${{ parameters.osMenu }}
        imageVarFile: ${{ parameters.imageVarFile }}
        providerMenu: ${{ parameters.providerMenu }}
        runtime: ${{ parameters.runtime }}

  - stage: ${{ provider.name }}Ansible
    displayName: ${{ provider.name }}Ansible
    condition: and( eq('${{ parameters.providerMenu }}', 'azure'), eq('${{ parameters.runtime }}', 'ansible') )
    jobs:
    - job: 'show_variables_ansible'
      steps:
      - script: |
          echo '${{ parameters.platform }}'
          echo '${{ parameters.imagesMenu }}'
          echo '${{ parameters.osMenu }}'
          echo '${{ parameters.imageVarFile }}'
          echo '${{ parameters.providerMenu }}'
          echo '${{ parameters.runtime }}'
          echo '${{ parameters.ansible }}'
        displayName: 'Ansible Vars'
    - job: ansibleInstall
      dependsOn: show_variables_ansible
      steps: 
      - script: |
          # VER=1.5.6
          # echo "Download File"
          # wget https://releases.hashicorp.com/packer/${VER}/packer_${VER}_linux_amd64.zip
          # echo "Unzip File and move to local bin"
          # sudo unzip packer_${VER}_linux_amd64.zip -d /usr/local/bin
          # echo "Get version"
          sudo apt-get update
          sudo apt-get install ansible -y
          sudo apt-get install python-pip -y
          pip install --upgrade pip
          pip install "pywinrm>=0.3.0"
          pip install "pyOpenSSL>=17.3.0"
          pip install requests-credssp
          sudo apt-get install python-winrm
          ansible --version
        displayName: 'ansibleInstall'
    - job: 'ansibleConfigure'
      dependsOn: ansibleInstall
      steps: 
      - script: |
          # VER=1.5.6
          # echo "Download File"
          # wget https://releases.hashicorp.com/packer/${VER}/packer_${VER}_linux_amd64.zip
          # echo "Unzip File and move to local bin"
          # sudo unzip packer_${VER}_linux_amd64.zip -d /usr/local/bin
          # echo "Get version"
          ansible --version
        displayName: 'ansibleConfigure'
    - job: 'ansibleRun'
      dependsOn: ansibleConfigure
      steps: 
      - script: |

          chmod +x ansible/ansible_setup.sh
          sudo ./ansible/ansible_setup.sh
          #./ado_packer_image.sh "${{ parameters.providerMenu }}" "${{ parameters.osMenu }}" "${{ parameters.imagesMenu }}" "${{ parameters.imageVarFile }}"
          #./ado_packer_image.sh "${{ parameters.providerMenu }}" "${{ parameters.osMenu }}" "$(ImageName)" "${{ parameters.imageVarFile }}"
          
          ansible -m win_ping windows
        displayName: 'ansibleRun'


  - stage: ${{ provider.name }}Services
    displayName: ${{ provider.name }}Services
    condition: and( ne('${{ parameters.tenant }}', 'default'), ne('${{ parameters.job }}', 'default') )
    jobs:
    - job: 'show_variables_services'
      steps:
      - script: |
          echo '${{ parameters.platform }}'
          echo '${{ parameters.imagesMenu }}'
          echo '${{ parameters.osMenu }}'
          echo '${{ parameters.imageVarFile }}'
          echo '${{ parameters.providerMenu }}'
          echo '${{ parameters.runtime }}'
          echo '${{ parameters.tenant }}'
          echo '${{ parameters.job }}'
        displayName: 'show_variables_services'
    - job: configCheck
      dependsOn: show_variables_services
      steps: 
      - script: |
          echo '${{ parameters.tenant }}'
          echo '${{ parameters.job }}'
        displayName: 'configCheck'
    - job: 'servicesRun'
      dependsOn: configCheck
      steps: 
      - script: |
          #aws ssm put-parameter --name "/builds/${packerProvider}/${packerOs}/${packerImage}/name" --value "${packerImageName}" --type String --overwrite
          #aws ssm put-parameter --name "/builds/${packerProvider}/${packerOs}/${packerImage}/id" --value "${packerImageId}" --type String --overwrite
          aws ssm get-parameter --name "MySecureStringParameter" --with-decryption
          #echo "s3://gitdonkey/devops/${packerImageName}.html"
          #aws s3 cp aliases.html "s3://gitdonkey/devops/${packerImageName}.html"
          #echo "s3://gitdonkey/devops/${packerImageName}.json"
          #aws s3 cp manifest.json "s3://gitdonkey/devops/${packerImageName}.json"
          #echo "s3://gitdonkey/devops/${packerImageName}_packer_log.json"
          #aws s3 cp packer.log "s3://gitdonkey/devops/${packerImageName}_packer_log.json"
          echo '${{ parameters.tenant }}'
          echo '${{ parameters.job }}'
        displayName: 'servicesRun'
    - job: 'servicesVerify'
      dependsOn: servicesRun
      steps: 
      - script: |
          echo '${{ parameters.tenant }}'
          echo '${{ parameters.job }}'
        displayName: 'servicesVerify'










#  - stage: ${{ provider.name }}Buildall
#    displayName: ${{ provider.name }} - Buildall
#    dependsOn: ${{ provider.name }}Init
#    condition: and( ne('${{ parameters.imagesMenu }}', 'all'), eq('${{ parameters.imagesMenu }}', 'rlgroup') )
#    jobs:
#    - template: /packer/images.yaml
#      parameters:
#        provider: ${{ provider.name }}
#        stage: build
#        imagesMenu: ${{ parameters.imagesMenu }}
#        osMenu: ${{ parameters.osMenu }}
#        imageVarFile: ${{ parameters.imageVarFile }}
#        providerMenu: ${{ parameters.providerMenu }}
#        runtime: ${{ parameters.runtime }}

#  - stage: ${{ provider.name }}Buildsingle
#    displayName: ${{ provider.name }} - Buildsingle
#    dependsOn: ${{ provider.name }}Init
#    condition: and( ne('${{ parameters.imagesMenu }}', 'all'), ne('${{ parameters.imagesMenu }}', 'rlgroup') )
#    jobs:
#    - template: /packer/images.yaml
#      parameters:
#        provider: ${{ provider.name }}
#        stage: build
#        imagesMenu: ${{ parameters.imagesMenu }}
#        osMenu: ${{ parameters.osMenu }}
#        imageVarFile: ${{ parameters.imageVarFile }}
#        providerMenu: ${{ parameters.providerMenu }}
#        runtime: ${{ parameters.runtime }}