stages:
- stage: 'Testing'
  jobs:
  - job: 'show_variables1'
    steps:
    - script: |
        echo 'one'
      displayName: 's1'
- ${{ each provider in parameters.providers }}:
  - stage: ${{ provider.name }}Init
    displayName: ${{ provider.name }} - Init
    dependsOn: Testing
    jobs:
    - job: init
      steps:
      - script: |
          echo ${{ provider.name }}Job1
        displayName: ${{ provider.name }}Job1
  - stage: ${{ provider.name }}Build
    displayName: ${{ provider.name }} - Build
    dependsOn: ${{ provider.name }}Init
    #condition: or( eq( variables['provider'], ${{ provider.name }}, eq( variables['provider'], ${{ provider.name }} ) )
    jobs:
    - job: job1
      steps:
      - script: |
          echo ${{ provider.name }}job1
        displayName: ${{ provider.name }}job1