stages:
- stage: 'Testing'
  jobs:
  - job: 'show_variables1'
    steps:
    - script: |
        echo '${{ parameters.imagesMenu }}'
        echo '${{ parameters.osMenu }}'
        echo '[${{ parameters.providers }}]'
        echo '$(provider)'

      displayName: 's1'

- ${{ each provider in parameters.providers }}:
  - stage: ${{ provider.name }}Init
    displayName: ${{ provider.name }} - Init
    dependsOn: Testing
    jobs:
    - job: initJob1
      steps:
      - script: |
          echo ${{ provider.name }}initJob1
        displayName: ${{ provider.name }}initJob1
  - stage: ${{ provider.name }}Build
    displayName: ${{ provider.name }} - Build
    dependsOn: ${{ provider.name }}Init
    condition: or( eq('${{ parameters.imagesMenu }}', 'all'), eq('${{ parameters.imagesMenu }}', 'test') )
    jobs:
    - job: buildjob1
      steps:
      - script: |
          echo ${{ provider.name }}buildjob1
        displayName: ${{ provider.name }}buildjob1
  - stage: ${{ provider.name }}Build2
    displayName: ${{ provider.name }} - Build2
    dependsOn: ${{ provider.name }}Build
    condition: or( eq('${{ parameters.imagesMenu }}', 'all'), eq('${{ parameters.imagesMenu }}', 'test') )
    jobs:
    - template: /packer/images.yaml
      parameters:
        provider: ${{ provider.name }}
        stage: build
        imagesMenu: ${{ parameters.imagesMenu }}
        osMenu: ${{ parameters.osMenu }}
        runtime: ${{ parameters.runtime }}
    #- job: ImageAvailJob
    #  steps: 
    #  - ${{ each test in parameters.imagesMenu }}:
    #    - script: echo ${{ test.name }}
    #      displayName: ${{ test.name }}ImagesAvailscript